"""Renamed Column

Revision ID: 453696f1ff2d
Revises: 
Create Date: 2025-02-01 23:32:35.381132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453696f1ff2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=200), nullable=False))
        batch_op.drop_column('column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
